INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRICE) VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'Producto 1', 'descripcion producto 1' , 25);
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRICE) VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'Producto 2', 'descripcion producto 2' , 30.5);
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRICE) VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'Producto 3', 'descripcion producto 3' , 40.8);
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRICE) VALUES (NEXT VALUE FOR PRODUCT_SEQ, 'Producto 4', 'descripcion producto 4' , 51.1);

